apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgdh-app
  namespace: argocd
spec:
    destination:
        namespace: bgdh
        server: https://kubernetes.default.svc
    project: default
    source:
        repoURL: https://github.com/Kim-Taesu/argo-example.git
        path: book/ch07/bgdh
        targetRevision: main
        helm:
            parameters:
                - name: app
                  value: $ARGOCD_APP_NAME
    syncPolicy: # 동기화 정책을 정의
        automated: # Argo CD 가 자동으로 저장소 내용과 동기화하도록 지정
            prune: true # 저장소 내용과 동기화된 리소스가 다르면 삭제
            selfHeal: false # 저장소 내용과 동기화된 리소스가 다르면 복구