apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
    log.level: debug
    registries.conf: |
        registries:
        - name: Docker Hub
          prefix: docker.io
          api_url: https://registry-1.docker.io
          credentials: pullsecret:argocd/dockerhub-secret
          insecure: yes
          defaultns: wstattaesukim
          default: true