apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgdk-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=wstattaesukim/bgd # 모니터링되는 이미지 이름
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds # git wkrur wmdaud dnlcl
    argocd-image-updater.argoproj.io/git-branch: main # 변경 사항을 푸시할 브랜치
spec:
    destination:
        namespace: bgdui
        server: https://kubernetes.default.svc
    project: default
    source:
        repoURL: https://github.com/Kim-Taesu/argo-example.git
        path: book/ch07/bgdui/bgdk
        targetRevision: main
    syncPolicy: # 동기화 정책을 정의
        automated: # Argo CD 가 자동으로 저장소 내용과 동기화하도록 지정
            prune: true # 저장소 내용과 동기화된 리소스가 다르면 삭제
            selfHeal: false # 저장소 내용과 동기화된 리소스가 다르면 복구