apiVersion: v1
kind: Secret
metadata:
  name: git-repository-secret-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  name: github-repository-ssh
  project: default
  url: git@github.com:Kim-Taesu/argo-example.git # 저장소 URL
  # public key : ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAn+X7xSQ9mULfESReYEUcu4EKeCnhN5IXDMraUF9F4T user@AL02357078-4.local
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAJ/l+8UkPZlC3xEkXmBFHLuBCngp4TeSFwzK2lBfReEwAAAKDVlFpu1ZRa
    bgAAAAtzc2gtZWQyNTUxOQAAACAJ/l+8UkPZlC3xEkXmBFHLuBCngp4TeSFwzK2lBfReEw
    AAAEB549Os0KF3A1a/uGKOpQSwbrGXSKvZSw98+CuXUZu/gwn+X7xSQ9mULfESReYEUcu4
    EKeCnhN5IXDMraUF9F4TAAAAF3VzZXJAQUwwMjM1NzA3OC00LmxvY2FsAQIDBAUG
    -----END OPENSSH PRIVATE KEY-----