apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app-sync
  namespace: argocd
spec:
    destination:
        namespace: bgd
        server: https://kubernetes.default.svc
    project: default
    source:
        repoURL: https://github.com/Kim-Taesu/argo-example.git
        path: book/ch07/bgd
        targetRevision: main
    syncPolicy: # 동기화 정책을 정의
        automated: # Argo CD 가 자동으로 저장소 내용과 동기화하도록 지정
            prune: true # 저장소 내용과 동기화된 리소스가 다르면 삭제
            selfHeal: false # 저장소 내용과 동기화된 리소스가 다르면 복구