apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bgd-application
  namespace: argocd
spec:
    generators:
    - list:
        elements:
        - cluster: staging
          url: https://kubernetes.default.svc
          location: default
        - cluster: prod
          url: https://kubernetes.default.svc
          location: app
    template:
        metadata:
            name: '{{ cluster }}-app'
        spec:
            project: default
            source:
                repoURL: https://github.com/Kim-Taesu/argo-example.git
                targetRevision: main
                path: book/ch08/{{cluster}}
            destination:
                server: '{{ url }}'
                namespace: '{{ location }}'
            syncPolicy:
                syncOptions:
                - CreateNamespace=true