apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bgd-application
  namespace: argocd
spec:
    generators:
    - git:
        repoURL: https://github.com/Kim-Taesu/argo-example.git
        revision: main
        directories:
        - path: book/ch08/bdg-gen/*
    template:
        metadata:
            name: '{{path[1]}}{{path[3]}'
        spec:
            project: default
            source:
                repoURL: https://github.com/Kim-Taesu/argo-example.git
                targetRevision: main
                path: '{{path}}'
            destination:
                server: https://kubernetes.default.svc
                namespace: '{{ path.basename }}'